### ISSUE TITLE
https://github.com/mnaibei/Capstone-2.git

### ISSUE THREAD

**Issue by mnaibei** [mnaibei/Capstone-2#21]
Hello we are a group of 2 students

**Comment by didierganthier** [comment]
Hi Team,

While you put in a lot of hard work in this project, unfortunately, I cannot proceed with reviewing your code.

<img src="https://media.giphy.com/media/HOTfexLzbar5u/giphy.gif" />

## Invalid Code Review Request 🚫

- You should have sent a link to the GitHub issue that has a link to the GitHub project. Please edit the issue to reflect that or submit a new one. 👍🏽 

Your Code Review Request will be marked as invalid in your Dashboard, but don't worry you can always try again! 💪

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

--------

_Invalid Code Review Request **does not count** towards the code reviews limit._
