### ISSUE TITLE
Kanban board setup for Capstone project

### ISSUE THREAD

**Issue by mnaibei** [mnaibei/Capstone-2#22]
Hello, we are a team of 2 students.
Link to our repo: https://github.com/mnaibei/Capstone-2

**Comment by emmiiorji** [comment]
Hi @mnaibei and @Otegaa, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220870678-4f45b7ed-1d79-4e6a-9338-da59224b2cbc.gif'/>
</div>

You have submitted an issue without a link to your [GitHub project](https://github.com/mnaibei/Capstone-2/projects?query=is%3Aopen). Kindly create a GitHub project which should be a copy of [this template board](https://github.com/microverseinc/curriculum-javascript/projects/1).

The project should appear in the projects tab:
![image](https://user-images.githubusercontent.com/20554583/232496151-9c87dc23-afc4-4421-aa81-7b5b594ec658.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
